<header>
    <h2>Adicionar/Editar aluno</h2>
</header>

<form action="" method="post" ENCTYPE="multipart/form-data">
	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Nome</label> <input type="text"
				class="form-control" id="nome" name="nome"
				value="<?php echo isset($view_nome) ? $view_nome: '' ; ?>">
		</div>
	</div>
	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Email</label> <input type="text"
				class="form-control" id="email" name="email"
				placeholder="informe um email valido"
				value="<?php echo isset($view_email) ? $view_email : '' ; ?>">
		</div>
	</div>
	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Telefone</label> <input type="text"
				class="form-control" id="telefone" placeholder="informe um telefone"
				name="telefone"
				value="<?php echo isset($view_telefone) ? $view_telefone : '' ; ?>">
		</div>
	</div>
	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Endereço</label> <input type="text"
				class="form-control" id="endereco" placeholder="informe o endereço"
				name="endereco"
				value="<?php echo isset($view_endereco) ? $view_endereco : '' ; ?>">
		</div>
	</div>


	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">CPF</label> <input type="text"
				class="form-control" id="CPF" placeholder="informe um CPF valido"
				name="CPF" value="<?php echo isset($view_CPF) ? $view_CPF : '' ; ?>">
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">id_usuario</label> <input type="text"
				class="form-control" id="id_usuario"
				placeholder="informe uma id numerica" name="id_usuario"
				value="<?php echo isset($view_id_usuario) ? $view_id_usuario : '' ; ?>">
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Arquivo</label> 
			<input type="file" class="form-control" id="arquivo" name="arquivo">
			
			<?php if(isset($view_file)){?>
				<a href="<?php echo $view_file;?>">Visualizar Imagem</a>
				<input type="hidden" name="arquivo_existe" value="<?php echo $view_file;?>" />
			<?php } ?>
			
		</div>
	</div>


	<div class="row">
		<div class="col-md-12">
			<input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
				<a onClick="history.go(-1)"	class="btn btn-default">Cancelar</a>
		</div>
	</div>
</form>
</div>