		</section>	
		<div id="main" class="container-fluid" style="margin-top: 50px">
 
 	<div id="top" class="row">
		<div class="col-sm-3">
			<h2>Cursos</h2>
		</div>
		<div class="col-sm-6">
			
			<div class="input-group h2">
				<input name="data[search]" class="form-control" id="search" type="text" placeholder="Pesquisar Itens">
			<span class="input-group-btn">
					<button class="btn btn-primary" type="submit">Pesquisar
					</button>
				</span>
			</div>
			
		</div>
		<div class="col-sm-3">
			<a href="http://localhost/maestro2/cursos/adicionar" class="btn btn-primary pull-right h2">Novo Item</a>
		</div>
	</div> <!-- /#top -->
 
 
 	<hr>
 	<div id="list" class="row">
	
	<div class="table-responsive col-md-12">
		<table class="table table-striped" cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Descrição</th>
					<th>Carga horaria</th>
					<th>Periodo</th>
					<th>Professor</th>
					<th>Lotação</th>
					<th>Inicio</th>
					<th>Fim</th>
					<th class="actions">Ações</th>
				</tr>
			</thead>
			<tbody>
			
			<?php
	  		foreach ($view_cursos as $linha){
	  		?>
	  	<tr>
	    	<td><?php echo $linha['titulo'];?></td>
	    	<td><?php echo $linha['descricao'];?></td>
	    	<td><?php echo $linha['carga_horaria'];?></td>
	    	<td><?php echo $linha['periodo'];?></td>
	    	<td><?php echo $linha['professor'];?></td>
	    	<td><?php echo $linha['lotacao'];?></td>
	    	<td><?php echo $linha['data_inicio'];?></td>
	    	<td><?php echo $linha['data_fim'];?></td>
	    	<td class="actions">
				<a class="btn btn-success btn-xs" href="http://localhost/maestro2/cursos/visualizar/id/<?php echo $linha['id'];?>">Visualizar</a>
				<a class="btn btn-warning btn-xs" href="http://localhost/maestro2/cursos/editar/id/<?php echo $linha['id'];?>">Editar</a>
				<a class="btn btn-danger btn-xs"  onclick="return confirm('confirmar exclusão de: <?php echo $linha['titulo'];?>');" href="http://localhost/maestro2/cursos/deletar/id/<?php echo $linha['id'];?>">Excluir</a>			
			</td>
	    		    	
	  	</tr>	 	 	  	
	  	
	  	<?php
	  	}?>
	
	</div> <!-- /#list -->
	
	<div id="bottom" class="row">
		<div class="col-md-12">
			<ul class="pagination">
				<li class="disabled"><a>&lt; Anterior</a></li>
				<li class="disabled"><a>1</a></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li class="next"><a href="#" rel="next">Próximo &gt;</a></li>
			</ul><!-- /.pagination -->
		</div>
	</div> <!-- /#bottom -->
 </div>			
	</body>
</html>