		</section>	
		<div id="main" class="container-fluid" style="margin-top: 50px">
 
 	<div id="top" class="row">
		<div class="col-sm-3">
			<h2>Itens</h2>
		</div>
		<div class="col-sm-6">
			
			<div class="input-group h2">
				<input name="data[search]" class="form-control" id="search" type="text" placeholder="Pesquisar Itens">
			<span class="input-group-btn">
					<button class="btn btn-primary" type="submit">Pesquisar
					</button>
				</span>
			</div>
			
		</div>
		<div class="col-sm-3">
			<a href="#" class="btn btn-primary pull-right h2">Novo Item</a>
		</div>
	</div> <!-- /#top -->
 
 
 	<hr>
 	<div id="list" class="row">
	
	<div class="table-responsive col-md-12">
		<table class="table table-striped" cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<th>ID</th>
					<th>Nome</th>
					<th>Sexo</th>
					<th>Data</th>
					<th class="actions">Ações</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1001</td>
					<td>Teste1</td>
					<td>Masculino</td>
					<td>01/10/2016</td>
					<td class="actions">
						<a class="btn btn-success btn-xs" href="#">Visualizar</a>
						<a class="btn btn-warning btn-xs" href="#">Editar</a>
						<a class="btn btn-danger btn-xs" href="#" data-toggle="modal" data-target="#delete-modal">Excluir</a>
					</td>
				</tr>
				<tr>
					<td>1002</td>
					<td>Teste2</td>
					<td>Feminino</td>
					<td>01/10/2016</td>
					<td class="actions">
						<a class="btn btn-success btn-xs" href="#">Visualizar</a>
						<a class="btn btn-warning btn-xs" href="#">Editar</a>
						<a class="btn btn-danger btn-xs" href="#" data-toggle="modal" data-target="#delete-modal">Excluir</a>
					</td>
				</tr>
				<tr>
					<td>1003</td>
					<td>Teste3</td>
					<td>Masculino</td>
					<td>01/10/2016</td>
					<td class="actions">
						<a class="btn btn-success btn-xs" href="#">Visualizar</a>
						<a class="btn btn-warning btn-xs" href="#">Editar</a>
						<a class="btn btn-danger btn-xs" href="#" data-toggle="modal" data-target="#delete-modal">Excluir</a>
					</td>
				</tr>
				<tr>
					<td>1004</td>
					<td>Teste4</td>
					<td>Feminino</td>
					<td>01/10/2016</td>
					<td class="actions">
						<a class="btn btn-success btn-xs" href="#">Visualizar</a>
						<a class="btn btn-warning btn-xs" href="#">Editar</a>
						<a class="btn btn-danger btn-xs" href="#" data-toggle="modal" data-target="#delete-modal">Excluir</a>
					</td>
				</tr>
				<tr>
					<td>1005</td>
					<td>Teste5</td>
					<td>Masculino</td>
					<td>01/10/2016</td>
					<td class="actions">
						<a class="btn btn-success btn-xs" href="#">Visualizar</a>
						<a class="btn btn-warning btn-xs" href="#">Editar</a>
						<a class="btn btn-danger btn-xs" href="#" data-toggle="modal" data-target="#delete-modal">Excluir</a>
					</td>
				</tr>
				<tr>
					<td>1006</td>
					<td>Teste6</td>
					<td>Feminino</td>
					<td>01/10/2016</td>
					<td class="actions">
						<a class="btn btn-success btn-xs" href="#">Visualizar</a>
						<a class="btn btn-warning btn-xs" href="#">Editar</a>
						<a class="btn btn-danger btn-xs" href="#" data-toggle="modal" data-target="#delete-modal">Excluir</a>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	
	</div> <!-- /#list -->
	
	<div id="bottom" class="row">
		<div class="col-md-12">
			<ul class="pagination">
				<li class="disabled"><a>&lt; Anterior</a></li>
				<li class="disabled"><a>1</a></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li class="next"><a href="#" rel="next">Próximo &gt;</a></li>
			</ul><!-- /.pagination -->
		</div>
	</div> <!-- /#bottom -->
 </div>			
	</body>
</html>