<header>
    <h2>Adicionar/Editar professor</h2>
</header>

<form action="" method="post">
	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Nome</label> <input type="text"
				class="form-control" id="funcionario" name="funcionario" 
				value="<?php echo isset($view_funcionario) ? $view_funcionario: '' ; ?>">
		</div>
	</div>
	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Função</label> <input type="text"
				class="form-control" id="funcao" name="funcao"
				value="<?php echo isset($view_funcao) ? $view_funcao : '' ; ?>">
		</div>
	</div>
	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Ativo</label> <input
				type="text" class="form-control" id="ativo"
				placeholder="0 desativado 1 para ativado" name="ativo"
				value="<?php echo isset($view_ativo) ? $view_ativo : '' ; ?>">
		
	
	<div class="row">
		<div class="form-group col-md-5">
			<label for="exampleInputEmail1">Id_usuario</label> <input type="text"
				class="form-control" id="id_usuario" name="id_usuario"
				value="<?php echo isset($view_id_usuario) ? $view_id_usuario : '' ; ?>">
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<input type="submit" class="btn btn-primary" name="btsalvar"
				value="Salvar" /> <a onClick="history.go(-1)"
				class="btn btn-default">Cancelar</a>
		</div>
	</div>
</form>
</div>

